#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-panel
Version  : 4.13.0
Release  : 25
URL      : http://archive.xfce.org/src/xfce/xfce4-panel/4.13/xfce4-panel-4.13.0.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfce4-panel/4.13/xfce4-panel-4.13.0.tar.bz2
Summary  : Library for the Xfce Panel
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: xfce4-panel-bin
Requires: xfce4-panel-lib
Requires: xfce4-panel-data
Requires: xfce4-panel-doc
Requires: xfce4-panel-locales
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(garcon-gtk3-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libwnck-1.0)
BuildRequires : pkgconfig(libwnck-3.0)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(x11)
BuildRequires : sed
Patch1: 0001-Implement-default-panel-layout.patch

%description


%package bin
Summary: bin components for the xfce4-panel package.
Group: Binaries
Requires: xfce4-panel-data

%description bin
bin components for the xfce4-panel package.


%package data
Summary: data components for the xfce4-panel package.
Group: Data

%description data
data components for the xfce4-panel package.


%package dev
Summary: dev components for the xfce4-panel package.
Group: Development
Requires: xfce4-panel-lib
Requires: xfce4-panel-bin
Requires: xfce4-panel-data
Provides: xfce4-panel-devel

%description dev
dev components for the xfce4-panel package.


%package doc
Summary: doc components for the xfce4-panel package.
Group: Documentation

%description doc
doc components for the xfce4-panel package.


%package lib
Summary: lib components for the xfce4-panel package.
Group: Libraries
Requires: xfce4-panel-data

%description lib
lib components for the xfce4-panel package.


%package locales
Summary: locales components for the xfce4-panel package.
Group: Default

%description locales
locales components for the xfce4-panel package.


%prep
%setup -q -n xfce4-panel-4.13.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1495726460
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1495726460
rm -rf %{buildroot}
%make_install
%find_lang xfce4-panel
## make_install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/. && rmdir %{buildroot}%{_sysconfdir}
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/panel/migrate
/usr/lib64/xfce4/panel/wrapper-1.0
/usr/lib64/xfce4/panel/wrapper-2.0

%files bin
%defattr(-,root,root,-)
/usr/bin/xfce4-panel
/usr/bin/xfce4-popup-applicationsmenu
/usr/bin/xfce4-popup-directorymenu
/usr/bin/xfce4-popup-windowmenu

%files data
%defattr(-,root,root,-)
/usr/share/applications/panel-desktop-handler.desktop
/usr/share/applications/panel-preferences.desktop
/usr/share/icons/hicolor/16x16/apps/xfce4-panel-menu.png
/usr/share/icons/hicolor/16x16/apps/xfce4-panel.png
/usr/share/icons/hicolor/22x22/apps/xfce4-panel-menu.png
/usr/share/icons/hicolor/22x22/apps/xfce4-panel.png
/usr/share/icons/hicolor/24x24/apps/xfce4-panel-menu.png
/usr/share/icons/hicolor/24x24/apps/xfce4-panel.png
/usr/share/icons/hicolor/32x32/apps/xfce4-panel-menu.png
/usr/share/icons/hicolor/32x32/apps/xfce4-panel.png
/usr/share/icons/hicolor/48x48/apps/xfce4-panel-menu.png
/usr/share/icons/hicolor/48x48/apps/xfce4-panel.png
/usr/share/icons/hicolor/scalable/apps/xfce4-panel.svg
/usr/share/xdg/xfce4/panel/default.xml
/usr/share/xfce4/panel/plugins/actions.desktop
/usr/share/xfce4/panel/plugins/applicationsmenu.desktop
/usr/share/xfce4/panel/plugins/clock.desktop
/usr/share/xfce4/panel/plugins/directorymenu.desktop
/usr/share/xfce4/panel/plugins/launcher.desktop
/usr/share/xfce4/panel/plugins/pager.desktop
/usr/share/xfce4/panel/plugins/separator.desktop
/usr/share/xfce4/panel/plugins/showdesktop.desktop
/usr/share/xfce4/panel/plugins/systray.desktop
/usr/share/xfce4/panel/plugins/tasklist.desktop
/usr/share/xfce4/panel/plugins/windowmenu.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/libxfce4panel-config.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/libxfce4panel-enum-types.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/libxfce4panel-enums.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/libxfce4panel.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-arrow-button.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-hvbox.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-convenience.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-image.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-macros-46.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-macros.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-plugin-provider.h
/usr/include/xfce4/libxfce4panel-1.0/libxfce4panel/xfce-panel-plugin.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/libxfce4panel-config.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/libxfce4panel-enum-types.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/libxfce4panel-enums.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/libxfce4panel.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-arrow-button.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-convenience.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-image.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-macros-46.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-macros.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-plugin-provider.h
/usr/include/xfce4/libxfce4panel-2.0/libxfce4panel/xfce-panel-plugin.h
/usr/lib64/libxfce4panel-1.0.so
/usr/lib64/libxfce4panel-2.0.so
/usr/lib64/pkgconfig/libxfce4panel-1.0.pc
/usr/lib64/pkgconfig/libxfce4panel-2.0.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/libxfce4panel-2.0/XfceArrowButton.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/XfcePanelImage.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/XfcePanelPlugin.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/api-index-4-6.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/api-index-4-8.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/api-index-deprecated.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/api-index-full.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/home.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/index.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/left-insensitive.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/left.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-2.0.devhelp2
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Commonly-used-plugin-macros.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Convenience-Functions.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-GObject-Oriented-Panel-Plugin-Registers-Macros.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Panel-Plugin-Register-Macros-(4.6-Style).html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Panel-Plugin-Register-Macros.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Standard-Enumerations.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-Version-Information.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-fundamentals.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-miscelleanous.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-plugins.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/libxfce4panel-widgets.html
/usr/share/gtk-doc/html/libxfce4panel-2.0/right-insensitive.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/right.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/style.css
/usr/share/gtk-doc/html/libxfce4panel-2.0/up-insensitive.png
/usr/share/gtk-doc/html/libxfce4panel-2.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxfce4panel-1.0.so.4
/usr/lib64/libxfce4panel-1.0.so.4.0.0
/usr/lib64/libxfce4panel-2.0.so.4
/usr/lib64/libxfce4panel-2.0.so.4.0.0
/usr/lib64/xfce4/panel/plugins/libactions.so
/usr/lib64/xfce4/panel/plugins/libapplicationsmenu.so
/usr/lib64/xfce4/panel/plugins/libclock.so
/usr/lib64/xfce4/panel/plugins/libdirectorymenu.so
/usr/lib64/xfce4/panel/plugins/liblauncher.so
/usr/lib64/xfce4/panel/plugins/libpager.so
/usr/lib64/xfce4/panel/plugins/libseparator.so
/usr/lib64/xfce4/panel/plugins/libshowdesktop.so
/usr/lib64/xfce4/panel/plugins/libsystray.so
/usr/lib64/xfce4/panel/plugins/libtasklist.so
/usr/lib64/xfce4/panel/plugins/libwindowmenu.so

%files locales -f xfce4-panel.lang
%defattr(-,root,root,-)

